use super::types::{App, ActivePanel};
use ratatui::text::{Line, Span};
use ratatui::style::{Style, Color, Modifier};

impl App {
    pub fn panel_help_lines(&self) -> Vec<Line<'static>> {
        let y = Style::default().fg(Color::Yellow).add_modifier(Modifier::BOLD);

        match self.ui.active_panel {
            ActivePanel::Models => vec![
                Line::from(Span::styled("MODELS PANEL", y)),
                Line::from(""),
                Line::from("Displays your local GGUF models and their status."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k / Arrow keys", y), Span::raw("  Navigate model list")]),
                Line::from(vec![Span::styled("Enter / l", y), Span::raw("  Load selected model into server")]),
                Line::from(vec![Span::styled("u", y), Span::raw("  Unload model from server")]),
                Line::from(vec![Span::styled("Ctrl+D", y), Span::raw("  Delete model (with confirmation)")]),
                Line::from(""),
                Line::from("In search mode (/):"),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Execute search")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Exit search")]),
                Line::from(vec![Span::styled("l", y), Span::raw("  View available GGUF files")]),
                Line::from(vec![Span::styled("S", y), Span::raw("  Cycle sort order (Relevance/Downloads/Likes/Trending/Created)")]),
                Line::from(vec![Span::styled("B", y), Span::raw("  Go back one page")]),
                Line::from(vec![Span::styled("Down at bottom", y), Span::raw("  Load more results (infinite scroll)")]),
                Line::from(vec![Span::styled("R", y), Span::raw("  Fetch and view README")]),
                Line::from(""),
                Line::from(vec![Span::styled("Shift+← / →", y), Span::raw("  Resize panel split (20%-80%)")]),
                Line::from(vec![Span::styled("Mouse drag on border", y), Span::raw("  Resize panel split")]),
                Line::from(""),
                Line::from(vec![Span::styled("Shift+A", y), Span::raw("  About box (GPLv3)")]),
            ],
            ActivePanel::Log => vec![
                Line::from(Span::styled("LOG PANEL", y)),
                Line::from(""),
                Line::from("Live output from the llama.cpp server."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k / Arrow keys", y), Span::raw("  Scroll log (Manual mode)")]),
                Line::from(vec![Span::styled("f", y), Span::raw("  Toggle Follow mode")]),
                Line::from(vec![Span::styled("g", y), Span::raw("  Jump to top (Manual mode)")]),
                Line::from(vec![Span::styled("G", y), Span::raw("  Jump to bottom (Follow mode)")]),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Expand log (fills screen)")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Collapse log")]),
                Line::from(""),
                Line::from(vec![Span::styled("Shift+A", y), Span::raw("  About box (GPLv3)")]),
            ],
            ActivePanel::ServerSettings => {
                vec![
                    Line::from(Span::styled("SERVER SETTINGS", y)),
                    Line::from(""),
                    Line::from("Configuration for the llama.cpp server."),
                    Line::from(""),
                    Line::from(vec![Span::styled("j / k", y), Span::raw("  Select setting")]),
                    Line::from(vec![Span::styled("Enter", y), Span::raw("  Toggle value")]),
                    Line::from(vec![Span::styled("Left / Right", y), Span::raw("  Adjust value")]),
                    Line::from(""),
                    Line::from(vec![Span::styled("Host", y), Span::raw("  Bind address (127.0.0.1 or 0.0.0.0)")]),
                    Line::from(vec![Span::styled("Backend", y), Span::raw("  Acceleration backend (cpu / vulkan / rocm)")]),
                    Line::from(vec![Span::styled("Threads", y), Span::raw("  CPU threads for generation (1 to max)")]),
                    Line::from(vec![Span::styled("Threads Batch", y), Span::raw("  CPU threads for batch processing (1 to 32)")]),
                    Line::from(vec![Span::styled("Mode", y), Span::raw("  Server mode (Normal / Router)")]),
                    Line::from(vec![Span::styled("API Endpoint", y), Span::raw("  Enable API proxy (True/False)")]),
                    Line::from(vec![Span::styled("API Port", y), Span::raw(self.get_api_port_str())]),
                    Line::from(""),
                    Line::from(vec![Span::styled("Shift+A", y), Span::raw("  About box (GPLv3)")]),
                ]
            }
            ActivePanel::LlmSettings => vec![
                Line::from(Span::styled("LLM SETTINGS", y)),
                Line::from(""),
                Line::from("Fine-tuned settings for loading and running a model."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k", y), Span::raw("  Navigate settings")]),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Apply value")]),
                Line::from(vec![Span::styled("Left / Right", y), Span::raw("  Adjust value")]),
                Line::from(vec![Span::styled("0-9, -, .", y), Span::raw("  Type numeric value  ·  Ctrl+F7/8/9 switch panels")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Cancel edit")]),
                Line::from(""),
                Line::from(vec![Span::styled("Ctrl+S", y), Span::raw("  Save settings for selected model")]),
                Line::from(vec![Span::styled("Ctrl+R", y), Span::raw("  Reset to defaults")]),
                Line::from(vec![Span::styled("Ctrl+E", y), Span::raw("  Toggle enabled/disabled")]),
                Line::from(""),
                Line::from(vec![Span::styled("--- Loading ---", y)]),
                Line::from(vec![Span::styled("Context", y), Span::raw("  Context window size in tokens. Determines how much of the conversation history is kept in memory. A larger context allows longer conversations but uses more RAM. Typical: 8192-65536 depending on model and RAM.")]),
                Line::from(vec![Span::styled("Prompt", y), Span::raw("  System prompt preset. Pre-configured prompts that shape how the model behaves (e.g., 'coder', 'assistant', 'creative'). Affects the model's personality and output style.")]),
                Line::from(vec![Span::styled("Keep in memory", y), Span::raw("  Lock model weights in RAM (mlock). Prevents the OS from swapping model weights to disk. Slows model load time but ensures faster inference once loaded. Useful for repeated use.")]),
                Line::from(""),
                Line::from(vec![Span::styled("--- GPU Offload ---", y)]),
                Line::from(vec![Span::styled("GPU Layers", y), Span::raw("  How many model layers to offload to GPU. Arrow keys cycle: Auto → 1 → 2 → ... → N → All → Auto. Auto lets llama.cpp decide based on VRAM. All loads every layer (999). Specific number sets exact offload count.")]),
                Line::from(vec![Span::styled("Flash Attention", y), Span::raw("  Enable Flash Attention (flash-attn) for faster inference. Requires compatible GPU (Ampere+ / Ada). Significantly speeds up long-context inference. Only works with certain GGUF formats.")]),
                Line::from(vec![Span::styled("KV Cache Offload", y), Span::raw("  Offload KV cache to RAM when GPU memory is full. Allows larger batch sizes and contexts at the cost of some speed. Useful when VRAM is limited but you still want longer conversations.")]),
                Line::from(vec![Span::styled("Cache Type K / V", y), Span::raw("  Quantization precision for KV cache (K = keys, V = values). Lower precision (e.g., Q4, Q8) saves VRAM but may slightly reduce quality. Default is usually FP16. Use lower values if running out of VRAM.")]),
                Line::from(vec![Span::styled("Active Experts", y), Span::raw("  Number of MoE (Mixture of Experts) experts to activate per token. -1 = auto (all active). Reducing this speeds up inference for MoE models like Mixtral but may reduce quality. Typical: 2-8 for Mixtral.")]),
                Line::from(""),
                Line::from(vec![Span::styled("--- Evaluation ---", y)]),
                Line::from(vec![Span::styled("Eval Batch", y), Span::raw("  Batch size for evaluation (inference). Larger batches use more VRAM but can improve throughput via parallelism. Small values (1-8) for low VRAM, larger (16-128) for high VRAM setups.")]),
                Line::from(vec![Span::styled("Unified KV", y), Span::raw("  Share KV cache across sequences. Reduces VRAM usage when running multiple requests by reusing allocated cache. May slightly reduce performance but enables more concurrent users.")]),
                Line::from(vec![Span::styled("Max Concurrent Pred", y), Span::raw("  Maximum number of models that can run simultaneously. Press Enter to open a picker that shows how context length divides per model. Each model needs its own VRAM/CPU resources.")]),
                Line::from(""),
                Line::from(vec![Span::styled("--- Sampling ---", y)]),
                Line::from(vec![Span::styled("Seed", y), Span::raw("  Random seed for reproducible outputs. -1 = random (default). Set to a fixed value for deterministic, repeatable responses — useful for debugging or testing prompts.")]),
                Line::from(vec![Span::styled("Temp", y), Span::raw("  Sampling temperature. Controls creativity: 0 = deterministic (most predictable), 0.7 = balanced, 1.0+ = creative. Lower values produce more focused, factual outputs. Typical: 0.7-0.9 for general use.")]),
                Line::from(vec![Span::styled("Top-k", y), Span::raw("  Only consider the top k most likely tokens at each step. Smaller top-k (e.g., 10-40) makes output more deterministic. Larger values allow more variety. Typical: 40-50. Set to 0 to disable.")]),
                Line::from(vec![Span::styled("Top-p", y), Span::raw("  Nucleus sampling: only consider tokens whose cumulative probability reaches p. Smaller top-p (e.g., 0.9) is more conservative, larger (e.g., 0.95-0.99) allows more variety. Often preferred over top-k. Typical: 0.9-0.95.")]),
                Line::from(vec![Span::styled("Min P", y), Span::raw("  Minimum probability threshold relative to the most likely token. Tokens below min_p * max_prob are excluded. A filter that's more principled than top-k/top-p for controlling diversity. Typical: 0.01-0.1.")]),
                Line::from(vec![Span::styled("Max Tokens", y), Span::raw("  Maximum number of tokens to generate in the response. Prevents runaway responses. Set to 0 or Disabled for no limit. Typical: 4096-8192 for chat, higher for code generation.")]),
                Line::from(""),
                Line::from(vec![Span::styled("Shift+A", y), Span::raw("  About box (GPLv3)")]),
            ],
            ActivePanel::ActiveModel => vec![
                Line::from(Span::styled("ACTIVE MODEL PANEL", y)),
                Line::from(""),
                Line::from("Displays metrics for the currently loaded model."),
                Line::from(""),
                Line::from("Shows Tokens/s, context usage (progress bar), CPU, RAM, and VRAM."),
            ],
            ActivePanel::ModelInfo => vec![
                Line::from(Span::styled("MODEL INFO PANEL", y)),
                Line::from(""),
                Line::from("GGUF metadata for the selected model."),
                Line::from(""),
                Line::from("Displays file name, size, architecture, layers, and training context."),
            ],
            ActivePanel::Profiles => vec![
                Line::from(Span::styled("PROFILES PANEL", y)),
                Line::from(""),
                Line::from("Saved presets of settings for quick switching."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k", y), Span::raw("  Select profile")]),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Apply profile settings")]),
                Line::from(vec![Span::styled("s", y), Span::raw("  Save current settings as new profile")]),
                Line::from(vec![Span::styled("d", y), Span::raw("  Delete user profile")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Back to settings")]),
            ],
            ActivePanel::SystemPromptPresets => vec![
                Line::from(Span::styled("SYSTEM PROMPT PRESETS", y)),
                Line::from(""),
                Line::from("Named system prompts for different use cases."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k", y), Span::raw("  Select preset")]),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Apply preset")]),
                Line::from(vec![Span::styled("e", y), Span::raw("  Edit selected preset")]),
                Line::from(vec![Span::styled("n", y), Span::raw("  Create new preset")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Back to settings")]),
            ],
            ActivePanel::SearchReadme => vec![
                Line::from(Span::styled("README PANEL", y)),
                Line::from(""),
                Line::from("README documentation for the selected model."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k / Arrow keys", y), Span::raw("  Scroll")]),
                Line::from(vec![Span::styled("h / l", y), Span::raw("  Scroll horizontally")]),
                Line::from(vec![Span::styled("Enter", y), Span::raw("  Expand to fullscreen")]),
                Line::from(vec![Span::styled("Esc", y), Span::raw("  Collapse / Exit")]),
            ],
            ActivePanel::Downloads => vec![
                Line::from(Span::styled("DOWNLOADS PANEL", y)),
                Line::from(""),
                Line::from("Active model downloads from HuggingFace."),
                Line::from(""),
                Line::from(vec![Span::styled("j / k / Arrow keys", y), Span::raw("  Select download")]),
                Line::from(vec![Span::styled("p", y), Span::raw("  Pause / Resume selected download")]),
                Line::from(vec![Span::styled("⌥C", y), Span::raw("  Cancel selected download")]),
            ],
        }
    }
}
