[book]
authors = ["agines"]
language = "en"
src = "src"
title = "LLM Manager"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/aginies/llmtui"
edit-url-template = "https://github.com/aginies/llmtui/edit/main/docs/{path}"
